### ISSUE TITLE
Rename ‘not found’ in tables to ‘unknown’. 

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_tabular_pages#121]
![screenshot from 2017-01-24 15-15-41](https://cloud.githubusercontent.com/assets/384894/22250652/fc233638-e247-11e6-8c6a-4b1a7bb3e46b.png)

Testers have raised the fact that 'unknown' might be more appropriate that 'Not found' since in examples as the one presented above a law definitely has a document number which is unknown, rather than not found.

**Comment by prustar** [comment]
@acorbi -- don't think this needs discussion -- 'Not found' has been raised as ambiguous as it's illogical that a legal document wouldn't have a document number, it must. The fact is that it's often difficult to uncover this information due to various reasons of mismanagement of data at the government institutional level and downwards. 

'Unknown' has been proposed by a number of people and consultants as being more appropriate because it's not like we haven't tried to find the data we just don't know what it is. 

It's a little bit same same but different but as users have raised it as unclear then it's not difficult to change the term. We then just need to be consistent with its application.

**Comment by acorbi** [comment]
@prustar ok, got it. will change now
