### ISSUE TITLE
removing columns in tables distorts filter and categories

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_tabular_pages#94]
@acorbi @Huyeng -- I tried to manipulate the columns again to remove the document type from the laws table and it defaulted then to document number: 

![image](https://cloud.githubusercontent.com/assets/14996905/21668843/d60a9bdc-d359-11e6-8388-f7a8054f45dd.png)

Please note that I've restored the column because categorising by document no. doesn't make sense.

**Comment by acorbi** [comment]
@prustar the tabular pages have a configuration setting that allows editors to specify the index of the column by which the rows are grouped by. It is called **group data column** , please read instructions on https://wiki.opendevelopmentmekong.net/partners:tabular_pages#creating_and_configuring_a_tabular_pages

**Comment by acorbi** [comment]
@prustar can we now close this?

**Comment by prustar** [comment]
@acorbi but I didn't change that? I simply removed the column, so what I expected was for just the column for Document type to be removed. Everything else should have remained the same.

**Comment by acorbi** [comment]
@prustar if the index of the **document type** (2) is specified on the **group data column** and you remove that column, then the next column **document number** (index 2 after you remove document type) will be used for grouping the entries, this is the expected behaviour. 

hence, if a column gets removed, the configuration should be adapted accordingly.

I'm closing this Issue.
